/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class matic_mladen_chatapplication_JNIxor */

#ifndef _Included_matic_mladen_chatapplication_JNIxor
#define _Included_matic_mladen_chatapplication_JNIxor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
